apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-prod/*
build:
  local:
    push: false
    # useDockerCLI: true
  # googleCloudBuild:
  #   projectId: ticketing-dev-jpj
  artifacts:
    - image: jibujacob/ecommerceclient
      context: ecommerceclient
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "**/*.*"
            dest: .
    - image: jibujacob/ecommerceauth
      context: ecommerceauth
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jibujacob/ecommerceproduct
      context: ecommerceproduct
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jibujacob/ecommercecart
      context: ecommercecart
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jibujacob/ecommerceorder
      context: ecommerceorder
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
