apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: ecommercejj.dev
      http:
        paths:
          # - path: /api/users/?(.*)
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: blogauth-srv
          #       port:
          #         number: 5001
          # - path: /api/posts/?(.*)
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: blogpost-srv
          #       port:
          #         number: 5001
          # - path: /api/categories/?(.*)
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: blogcategories-srv
          #       port:
          #         number: 5001
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: ecommerceclient-srv
                port:
                  number: 3000
