name: deploy-ecommerceorder

on:
  push:
    branches:
      - main
    paths:
      - "ecommerceorder/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # Added for Testing
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: cd ecommerceorder && docker buildx build --push --tag jibujacob/ecommerceorder --platform linux/amd64 .
      # - run: docker push jibujacob/blogclient
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save ecommerce
      - run: kubectl rollout restart deployment ecommerceorder-depl
