name: tests-ecommerceorder

on:
  pull_request:
    paths:
      - "ecommerceorder/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ecommerceorder && npm install && npm run test:ci
