name: tests-ecommerceauth

on:
  pull_request:
    paths:
      - "ecommerceauth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ecommerceauth && npm install && npm run test:ci
