name: tests-ecommerceproduct

on:
  pull_request:
    paths:
      - "ecommerceproduct/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ecommerceproduct && npm install && npm run test:ci
